### ISSUE TITLE
Little help

### ISSUE THREAD

**Issue by dotps1** [ctmalloy/ctmalloy.github.io#1]
Hi, great Jekyll theme.  Im not real Jekyll savvy, i was hoping you can help me out we two things on my site that i am using this theme, although tweaked a little bit.  you can find it here http://grposh.github.io.

First off, when the main panel is covered, you can still scroll down, and you can see the "Older Posts" paginator link, i would really like to hide that when the panel is covered.

second, when i am testing locally, when click the older posts in my events section, it renders just fine, but when i push it to the gh-pages, the page does not render at all.  its all messed up.

Anyway, any feed back or direction you may have would be most appreciated!  thanks again!

**Comment by dotps1** [comment]
maybe because paginate is supported any more?  https://github.com/jekyll/jekyll-paginate  maybe gh-pages has ditched it.

**Comment by dotps1** [comment]
and now my site is defaulting to the cover collapsed lol, awesome.

**Comment by ctmalloy** [comment]
I'm not too skilled with ghpages or Jekyll, was Lucky enough to spin up my
website without any errors one afternoon. Have you gone through the
templates/HTML for the theme to remove the "Older Posts" link? I can see
how it doesn't render properly, weird it only renders like that after you
push it.

**Comment by dotps1** [comment]
thanks for getting back to me, i missed that you had forked this from the creator.  Looks like there is a fix, its a little bit of work  I suggest you check it out before it get your instance as well!

https://github.com/joshgerdes/jekyll-uno/issues/72

thanks!

**Comment by dotps1** [comment]
there is also a way to fix the issue with the posts overflowing, https://github.com/joshgerdes/jekyll-uno/issues/42.

thanks.
